# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

name: it-kafka-registry
image:
  registry: docker.io
  repository: apicurio/apicurio-registry-mem
  tag: 1.3.1.Final
  pullPolicy: IfNotPresent
env:
  - name: QUARKUS_PROFILE
    value: "prod"
  - name: APPLICATION_ID
    value: "registry_id"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "it-kafka:9092"
  - name: APPLICATION_SERVER
    value: "localhost:9000"

## Service parameters
##
service:
  name: it-kafka-registry
  externalPort: 8081
  internalPort: 8080