# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: it-kafka
image:
  registry: docker.io
  repository: strimzi/kafka
  tag: 0.18.0-kafka-2.5.0
  pullPolicy: IfNotPresent
env:
  - name: KAFKA_ADVERTISED_LISTENERS
    value: "PLAINTEXT://it-kafka:9092"
  - name:  KAFKA_LISTENERS
    value: "PLAINTEXT://0.0.0.0:9092"
  - name: KAFKA_ZOOKEEPER_CONNECT
    value: it-kafka-zookeper:2181

## Service parameters
##
service:
  name: it-kafka
  externalPort: 9092
  internalPort: 9092