{{- if .Values.autoscaler -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ template "common.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ .Values.deployment.name }}
  minReplicas: {{ .Values.autoscaler.minReplicas | default "1" }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas | default "10" }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaler.cpu | default "60" }}
{{- end -}}