{{- if .Values.service.public}}{{- if eq .Values.service.public "true"}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
    weight: 100
  port:
    targetPort: {{ .Values.service.internalPort }}
{{- end }} {{- end }}