apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
    - name: "9092"
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    io.kompose.service: {{ .Values.service.name }}
  type: LoadBalancer
status:
  loadBalancer: {}